/**
 * Simple mapper for the mock data fields natively generated by panchang math.
 * In a real backend, the API would return these exact IDs, which translate easily.
 */
export const translatePanchangField = (value: string, languageCode: string): string => {
    if (languageCode === 'en' || !languageCode) return value; // Return as-is if English

    // Tithi mappings (Mock extensions)
    if (value.includes('Pratipada')) return 'प्रतिपदा';
    if (value.includes('Amavasya')) return 'अमावस्या';
    if (value.includes('Purnima')) return 'पौर्णिमा';
    if (value.includes('Ekadashi')) return 'एकादशी';

    // Paksha
    if (value.includes('Shukla')) return 'शुक्ल पक्ष';
    if (value.includes('Krishna')) return 'कृष्ण पक्ष';

    // Months
    if (value.includes('Chaitra')) return 'चैत्र';
    if (value.includes('Phalguna')) return 'फाल्गुन';

    // Nakshatras
    if (value.includes('Ashvini')) return 'अश्विनी';

    // Default fallback if we don't have a mapping yet for the massive list
    return value.replace(' (Mock)', '');
};
